// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cogs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCOGSSnapshot = `-- name: CreateCOGSSnapshot :one
INSERT INTO cogs_snapshots (
  recipe_id, overhead_id,
  ingredient_cost, labor_cost, overhead_cost,
  total_batch_cost, cost_per_unit, suggested_price, margin_pct, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, recipe_id, overhead_id, ingredient_cost, labor_cost, overhead_cost, total_batch_cost, cost_per_unit, suggested_price, margin_pct, calculated_at, notes
`

type CreateCOGSSnapshotParams struct {
	RecipeID       uuid.UUID   `json:"recipe_id"`
	OverheadID     pgtype.UUID `json:"overhead_id"`
	IngredientCost float64     `json:"ingredient_cost"`
	LaborCost      float64     `json:"labor_cost"`
	OverheadCost   float64     `json:"overhead_cost"`
	TotalBatchCost float64     `json:"total_batch_cost"`
	CostPerUnit    float64     `json:"cost_per_unit"`
	SuggestedPrice float64     `json:"suggested_price"`
	MarginPct      float64     `json:"margin_pct"`
	Notes          pgtype.Text `json:"notes"`
}

func (q *Queries) CreateCOGSSnapshot(ctx context.Context, arg CreateCOGSSnapshotParams) (CogsSnapshot, error) {
	row := q.db.QueryRow(ctx, createCOGSSnapshot,
		arg.RecipeID,
		arg.OverheadID,
		arg.IngredientCost,
		arg.LaborCost,
		arg.OverheadCost,
		arg.TotalBatchCost,
		arg.CostPerUnit,
		arg.SuggestedPrice,
		arg.MarginPct,
		arg.Notes,
	)
	var i CogsSnapshot
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.OverheadID,
		&i.IngredientCost,
		&i.LaborCost,
		&i.OverheadCost,
		&i.TotalBatchCost,
		&i.CostPerUnit,
		&i.SuggestedPrice,
		&i.MarginPct,
		&i.CalculatedAt,
		&i.Notes,
	)
	return i, err
}

const deleteCOGSSnapshot = `-- name: DeleteCOGSSnapshot :exec
DELETE FROM cogs_snapshots WHERE id = $1
`

func (q *Queries) DeleteCOGSSnapshot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCOGSSnapshot, id)
	return err
}

const listCOGSHistory = `-- name: ListCOGSHistory :many
SELECT
  cs.id,
  cs.recipe_id,
  cs.ingredient_cost,
  cs.labor_cost,
  cs.overhead_cost,
  cs.total_batch_cost,
  cs.cost_per_unit,
  cs.suggested_price,
  cs.margin_pct,
  cs.notes,
  cs.calculated_at,
  r.name       AS recipe_name,
  r.batch_yield,
  r.yield_unit
FROM cogs_snapshots cs
JOIN recipes r ON r.id = cs.recipe_id
ORDER BY cs.calculated_at DESC
LIMIT 100
`

type ListCOGSHistoryRow struct {
	ID             uuid.UUID          `json:"id"`
	RecipeID       uuid.UUID          `json:"recipe_id"`
	IngredientCost float64            `json:"ingredient_cost"`
	LaborCost      float64            `json:"labor_cost"`
	OverheadCost   float64            `json:"overhead_cost"`
	TotalBatchCost float64            `json:"total_batch_cost"`
	CostPerUnit    float64            `json:"cost_per_unit"`
	SuggestedPrice float64            `json:"suggested_price"`
	MarginPct      float64            `json:"margin_pct"`
	Notes          pgtype.Text        `json:"notes"`
	CalculatedAt   pgtype.Timestamptz `json:"calculated_at"`
	RecipeName     string             `json:"recipe_name"`
	BatchYield     int32              `json:"batch_yield"`
	YieldUnit      string             `json:"yield_unit"`
}

func (q *Queries) ListCOGSHistory(ctx context.Context) ([]ListCOGSHistoryRow, error) {
	rows, err := q.db.Query(ctx, listCOGSHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCOGSHistoryRow{}
	for rows.Next() {
		var i ListCOGSHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.IngredientCost,
			&i.LaborCost,
			&i.OverheadCost,
			&i.TotalBatchCost,
			&i.CostPerUnit,
			&i.SuggestedPrice,
			&i.MarginPct,
			&i.Notes,
			&i.CalculatedAt,
			&i.RecipeName,
			&i.BatchYield,
			&i.YieldUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCOGSHistoryByRecipe = `-- name: ListCOGSHistoryByRecipe :many
SELECT
  cs.id,
  cs.recipe_id,
  cs.ingredient_cost,
  cs.labor_cost,
  cs.overhead_cost,
  cs.total_batch_cost,
  cs.cost_per_unit,
  cs.suggested_price,
  cs.margin_pct,
  cs.notes,
  cs.calculated_at,
  r.name       AS recipe_name,
  r.batch_yield,
  r.yield_unit
FROM cogs_snapshots cs
JOIN recipes r ON r.id = cs.recipe_id
WHERE cs.recipe_id = $1
ORDER BY cs.calculated_at DESC
`

type ListCOGSHistoryByRecipeRow struct {
	ID             uuid.UUID          `json:"id"`
	RecipeID       uuid.UUID          `json:"recipe_id"`
	IngredientCost float64            `json:"ingredient_cost"`
	LaborCost      float64            `json:"labor_cost"`
	OverheadCost   float64            `json:"overhead_cost"`
	TotalBatchCost float64            `json:"total_batch_cost"`
	CostPerUnit    float64            `json:"cost_per_unit"`
	SuggestedPrice float64            `json:"suggested_price"`
	MarginPct      float64            `json:"margin_pct"`
	Notes          pgtype.Text        `json:"notes"`
	CalculatedAt   pgtype.Timestamptz `json:"calculated_at"`
	RecipeName     string             `json:"recipe_name"`
	BatchYield     int32              `json:"batch_yield"`
	YieldUnit      string             `json:"yield_unit"`
}

func (q *Queries) ListCOGSHistoryByRecipe(ctx context.Context, recipeID uuid.UUID) ([]ListCOGSHistoryByRecipeRow, error) {
	rows, err := q.db.Query(ctx, listCOGSHistoryByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCOGSHistoryByRecipeRow{}
	for rows.Next() {
		var i ListCOGSHistoryByRecipeRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.IngredientCost,
			&i.LaborCost,
			&i.OverheadCost,
			&i.TotalBatchCost,
			&i.CostPerUnit,
			&i.SuggestedPrice,
			&i.MarginPct,
			&i.Notes,
			&i.CalculatedAt,
			&i.RecipeName,
			&i.BatchYield,
			&i.YieldUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
