// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cogs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCOGSSnapshot = `-- name: CreateCOGSSnapshot :one
INSERT INTO cogs_snapshots (
  recipe_id, overhead_id,
  ingredient_cost, labor_cost, overhead_cost,
  total_batch_cost, cost_per_unit, suggested_price, margin_pct
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, recipe_id, overhead_id, ingredient_cost, labor_cost, overhead_cost, total_batch_cost, cost_per_unit, suggested_price, margin_pct, calculated_at
`

type CreateCOGSSnapshotParams struct {
	RecipeID       uuid.UUID   `json:"recipe_id"`
	OverheadID     pgtype.UUID `json:"overhead_id"`
	IngredientCost float64     `json:"ingredient_cost"`
	LaborCost      float64     `json:"labor_cost"`
	OverheadCost   float64     `json:"overhead_cost"`
	TotalBatchCost float64     `json:"total_batch_cost"`
	CostPerUnit    float64     `json:"cost_per_unit"`
	SuggestedPrice float64     `json:"suggested_price"`
	MarginPct      float64     `json:"margin_pct"`
}

func (q *Queries) CreateCOGSSnapshot(ctx context.Context, arg CreateCOGSSnapshotParams) (CogsSnapshot, error) {
	row := q.db.QueryRow(ctx, createCOGSSnapshot,
		arg.RecipeID,
		arg.OverheadID,
		arg.IngredientCost,
		arg.LaborCost,
		arg.OverheadCost,
		arg.TotalBatchCost,
		arg.CostPerUnit,
		arg.SuggestedPrice,
		arg.MarginPct,
	)
	var i CogsSnapshot
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.OverheadID,
		&i.IngredientCost,
		&i.LaborCost,
		&i.OverheadCost,
		&i.TotalBatchCost,
		&i.CostPerUnit,
		&i.SuggestedPrice,
		&i.MarginPct,
		&i.CalculatedAt,
	)
	return i, err
}

const listCOGSSnapshots = `-- name: ListCOGSSnapshots :many
SELECT
  cs.id, cs.recipe_id, cs.overhead_id, cs.ingredient_cost, cs.labor_cost, cs.overhead_cost, cs.total_batch_cost, cs.cost_per_unit, cs.suggested_price, cs.margin_pct, cs.calculated_at,
  r.name AS recipe_name
FROM cogs_snapshots cs
JOIN recipes r ON r.id = cs.recipe_id
ORDER BY cs.calculated_at DESC
LIMIT 50
`

type ListCOGSSnapshotsRow struct {
	ID             uuid.UUID          `json:"id"`
	RecipeID       uuid.UUID          `json:"recipe_id"`
	OverheadID     pgtype.UUID        `json:"overhead_id"`
	IngredientCost float64            `json:"ingredient_cost"`
	LaborCost      float64            `json:"labor_cost"`
	OverheadCost   float64            `json:"overhead_cost"`
	TotalBatchCost float64            `json:"total_batch_cost"`
	CostPerUnit    float64            `json:"cost_per_unit"`
	SuggestedPrice float64            `json:"suggested_price"`
	MarginPct      float64            `json:"margin_pct"`
	CalculatedAt   pgtype.Timestamptz `json:"calculated_at"`
	RecipeName     string             `json:"recipe_name"`
}

func (q *Queries) ListCOGSSnapshots(ctx context.Context) ([]ListCOGSSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listCOGSSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCOGSSnapshotsRow{}
	for rows.Next() {
		var i ListCOGSSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.OverheadID,
			&i.IngredientCost,
			&i.LaborCost,
			&i.OverheadCost,
			&i.TotalBatchCost,
			&i.CostPerUnit,
			&i.SuggestedPrice,
			&i.MarginPct,
			&i.CalculatedAt,
			&i.RecipeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCOGSSnapshotsByRecipe = `-- name: ListCOGSSnapshotsByRecipe :many
SELECT id, recipe_id, overhead_id, ingredient_cost, labor_cost, overhead_cost, total_batch_cost, cost_per_unit, suggested_price, margin_pct, calculated_at FROM cogs_snapshots
WHERE recipe_id = $1
ORDER BY calculated_at DESC
`

func (q *Queries) ListCOGSSnapshotsByRecipe(ctx context.Context, recipeID uuid.UUID) ([]CogsSnapshot, error) {
	rows, err := q.db.Query(ctx, listCOGSSnapshotsByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CogsSnapshot{}
	for rows.Next() {
		var i CogsSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.OverheadID,
			&i.IngredientCost,
			&i.LaborCost,
			&i.OverheadCost,
			&i.TotalBatchCost,
			&i.CostPerUnit,
			&i.SuggestedPrice,
			&i.MarginPct,
			&i.CalculatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
