// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingredients.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (name, sku, unit, price_per_unit, waste_pct, supplier_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, sku, unit, price_per_unit, waste_pct, supplier_id, updated_at
`

type CreateIngredientParams struct {
	Name         string      `json:"name"`
	Sku          pgtype.Text `json:"sku"`
	Unit         string      `json:"unit"`
	PricePerUnit float64     `json:"price_per_unit"`
	WastePct     float64     `json:"waste_pct"`
	SupplierID   pgtype.UUID `json:"supplier_id"`
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, createIngredient,
		arg.Name,
		arg.Sku,
		arg.Unit,
		arg.PricePerUnit,
		arg.WastePct,
		arg.SupplierID,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Unit,
		&i.PricePerUnit,
		&i.WastePct,
		&i.SupplierID,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIngredient = `-- name: DeleteIngredient :exec
DELETE FROM ingredients WHERE id = $1
`

func (q *Queries) DeleteIngredient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIngredient, id)
	return err
}

const getIngredient = `-- name: GetIngredient :one
SELECT id, name, sku, unit, price_per_unit, waste_pct, supplier_id, updated_at FROM ingredients WHERE id = $1
`

func (q *Queries) GetIngredient(ctx context.Context, id uuid.UUID) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredient, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Unit,
		&i.PricePerUnit,
		&i.WastePct,
		&i.SupplierID,
		&i.UpdatedAt,
	)
	return i, err
}

const listIngredients = `-- name: ListIngredients :many
SELECT id, name, sku, unit, price_per_unit, waste_pct, supplier_id, updated_at FROM ingredients ORDER BY name
`

func (q *Queries) ListIngredients(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, listIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ingredient{}
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Unit,
			&i.PricePerUnit,
			&i.WastePct,
			&i.SupplierID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngredient = `-- name: UpdateIngredient :one
UPDATE ingredients
SET name = $2, unit = $3, price_per_unit = $4, waste_pct = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, name, sku, unit, price_per_unit, waste_pct, supplier_id, updated_at
`

type UpdateIngredientParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Unit         string    `json:"unit"`
	PricePerUnit float64   `json:"price_per_unit"`
	WastePct     float64   `json:"waste_pct"`
}

func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, updateIngredient,
		arg.ID,
		arg.Name,
		arg.Unit,
		arg.PricePerUnit,
		arg.WastePct,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Unit,
		&i.PricePerUnit,
		&i.WastePct,
		&i.SupplierID,
		&i.UpdatedAt,
	)
	return i, err
}
