// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: labor.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createLaborProfile = `-- name: CreateLaborProfile :one
INSERT INTO labor_profiles (role, hourly_rate)
VALUES ($1, $2)
RETURNING id, role, hourly_rate
`

type CreateLaborProfileParams struct {
	Role       string  `json:"role"`
	HourlyRate float64 `json:"hourly_rate"`
}

func (q *Queries) CreateLaborProfile(ctx context.Context, arg CreateLaborProfileParams) (LaborProfile, error) {
	row := q.db.QueryRow(ctx, createLaborProfile, arg.Role, arg.HourlyRate)
	var i LaborProfile
	err := row.Scan(&i.ID, &i.Role, &i.HourlyRate)
	return i, err
}

const deleteLaborProfile = `-- name: DeleteLaborProfile :exec
DELETE FROM labor_profiles WHERE id = $1
`

func (q *Queries) DeleteLaborProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLaborProfile, id)
	return err
}

const getLaborProfile = `-- name: GetLaborProfile :one
SELECT id, role, hourly_rate FROM labor_profiles WHERE id = $1
`

func (q *Queries) GetLaborProfile(ctx context.Context, id uuid.UUID) (LaborProfile, error) {
	row := q.db.QueryRow(ctx, getLaborProfile, id)
	var i LaborProfile
	err := row.Scan(&i.ID, &i.Role, &i.HourlyRate)
	return i, err
}

const listLaborProfiles = `-- name: ListLaborProfiles :many
SELECT id, role, hourly_rate FROM labor_profiles ORDER BY role
`

func (q *Queries) ListLaborProfiles(ctx context.Context) ([]LaborProfile, error) {
	rows, err := q.db.Query(ctx, listLaborProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LaborProfile{}
	for rows.Next() {
		var i LaborProfile
		if err := rows.Scan(&i.ID, &i.Role, &i.HourlyRate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLaborProfile = `-- name: UpdateLaborProfile :one
UPDATE labor_profiles
SET role = $2, hourly_rate = $3
WHERE id = $1
RETURNING id, role, hourly_rate
`

type UpdateLaborProfileParams struct {
	ID         uuid.UUID `json:"id"`
	Role       string    `json:"role"`
	HourlyRate float64   `json:"hourly_rate"`
}

func (q *Queries) UpdateLaborProfile(ctx context.Context, arg UpdateLaborProfileParams) (LaborProfile, error) {
	row := q.db.QueryRow(ctx, updateLaborProfile, arg.ID, arg.Role, arg.HourlyRate)
	var i LaborProfile
	err := row.Scan(&i.ID, &i.Role, &i.HourlyRate)
	return i, err
}
