// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CogsSnapshot struct {
	ID             uuid.UUID          `json:"id"`
	RecipeID       uuid.UUID          `json:"recipe_id"`
	OverheadID     pgtype.UUID        `json:"overhead_id"`
	IngredientCost float64            `json:"ingredient_cost"`
	LaborCost      float64            `json:"labor_cost"`
	OverheadCost   float64            `json:"overhead_cost"`
	TotalBatchCost float64            `json:"total_batch_cost"`
	CostPerUnit    float64            `json:"cost_per_unit"`
	SuggestedPrice float64            `json:"suggested_price"`
	MarginPct      float64            `json:"margin_pct"`
	CalculatedAt   pgtype.Timestamptz `json:"calculated_at"`
}

type Ingredient struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Sku          pgtype.Text        `json:"sku"`
	Unit         string             `json:"unit"`
	PricePerUnit float64            `json:"price_per_unit"`
	WastePct     float64            `json:"waste_pct"`
	SupplierID   pgtype.UUID        `json:"supplier_id"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type LaborProfile struct {
	ID         uuid.UUID `json:"id"`
	Role       string    `json:"role"`
	HourlyRate float64   `json:"hourly_rate"`
}

type OverheadTemplate struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	PackagingCost float64   `json:"packaging_cost"`
	UtilitiesCost float64   `json:"utilities_cost"`
	OtherFixed    float64   `json:"other_fixed"`
}

type PriceHistory struct {
	ID           uuid.UUID   `json:"id"`
	IngredientID uuid.UUID   `json:"ingredient_id"`
	PricePerUnit float64     `json:"price_per_unit"`
	SupplierID   pgtype.UUID `json:"supplier_id"`
	RecordedAt   pgtype.Date `json:"recorded_at"`
}

type Recipe struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Category    pgtype.Text        `json:"category"`
	BatchYield  int32              `json:"batch_yield"`
	YieldUnit   string             `json:"yield_unit"`
	IsSubRecipe bool               `json:"is_sub_recipe"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RecipeLabor struct {
	ID             uuid.UUID `json:"id"`
	RecipeID       uuid.UUID `json:"recipe_id"`
	LaborProfileID uuid.UUID `json:"labor_profile_id"`
	Minutes        float64   `json:"minutes"`
}

type RecipeLine struct {
	ID           uuid.UUID   `json:"id"`
	RecipeID     uuid.UUID   `json:"recipe_id"`
	IngredientID pgtype.UUID `json:"ingredient_id"`
	SubRecipeID  pgtype.UUID `json:"sub_recipe_id"`
	Quantity     float64     `json:"quantity"`
	Unit         string      `json:"unit"`
}

type Supplier struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Contact   pgtype.Text        `json:"contact"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
