// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: overhead.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOverheadTemplate = `-- name: CreateOverheadTemplate :one
INSERT INTO overhead_templates (name, packaging_cost, utilities_cost, other_fixed)
VALUES ($1, $2, $3, $4)
RETURNING id, name, packaging_cost, utilities_cost, other_fixed
`

type CreateOverheadTemplateParams struct {
	Name          string  `json:"name"`
	PackagingCost float64 `json:"packaging_cost"`
	UtilitiesCost float64 `json:"utilities_cost"`
	OtherFixed    float64 `json:"other_fixed"`
}

func (q *Queries) CreateOverheadTemplate(ctx context.Context, arg CreateOverheadTemplateParams) (OverheadTemplate, error) {
	row := q.db.QueryRow(ctx, createOverheadTemplate,
		arg.Name,
		arg.PackagingCost,
		arg.UtilitiesCost,
		arg.OtherFixed,
	)
	var i OverheadTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PackagingCost,
		&i.UtilitiesCost,
		&i.OtherFixed,
	)
	return i, err
}

const deleteOverheadTemplate = `-- name: DeleteOverheadTemplate :exec
DELETE FROM overhead_templates WHERE id = $1
`

func (q *Queries) DeleteOverheadTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOverheadTemplate, id)
	return err
}

const getOverheadTemplate = `-- name: GetOverheadTemplate :one
SELECT id, name, packaging_cost, utilities_cost, other_fixed FROM overhead_templates WHERE id = $1
`

func (q *Queries) GetOverheadTemplate(ctx context.Context, id uuid.UUID) (OverheadTemplate, error) {
	row := q.db.QueryRow(ctx, getOverheadTemplate, id)
	var i OverheadTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PackagingCost,
		&i.UtilitiesCost,
		&i.OtherFixed,
	)
	return i, err
}

const listOverheadTemplates = `-- name: ListOverheadTemplates :many
SELECT id, name, packaging_cost, utilities_cost, other_fixed FROM overhead_templates ORDER BY name
`

func (q *Queries) ListOverheadTemplates(ctx context.Context) ([]OverheadTemplate, error) {
	rows, err := q.db.Query(ctx, listOverheadTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OverheadTemplate{}
	for rows.Next() {
		var i OverheadTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PackagingCost,
			&i.UtilitiesCost,
			&i.OtherFixed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOverheadTemplate = `-- name: UpdateOverheadTemplate :one
UPDATE overhead_templates
SET name = $2, packaging_cost = $3, utilities_cost = $4, other_fixed = $5
WHERE id = $1
RETURNING id, name, packaging_cost, utilities_cost, other_fixed
`

type UpdateOverheadTemplateParams struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	PackagingCost float64   `json:"packaging_cost"`
	UtilitiesCost float64   `json:"utilities_cost"`
	OtherFixed    float64   `json:"other_fixed"`
}

func (q *Queries) UpdateOverheadTemplate(ctx context.Context, arg UpdateOverheadTemplateParams) (OverheadTemplate, error) {
	row := q.db.QueryRow(ctx, updateOverheadTemplate,
		arg.ID,
		arg.Name,
		arg.PackagingCost,
		arg.UtilitiesCost,
		arg.OtherFixed,
	)
	var i OverheadTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PackagingCost,
		&i.UtilitiesCost,
		&i.OtherFixed,
	)
	return i, err
}
