// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: price_history.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPriceHistory = `-- name: CreatePriceHistory :one
INSERT INTO price_history (ingredient_id, price_per_unit, supplier_id)
VALUES ($1, $2, $3)
RETURNING id, ingredient_id, price_per_unit, supplier_id, recorded_at
`

type CreatePriceHistoryParams struct {
	IngredientID uuid.UUID   `json:"ingredient_id"`
	PricePerUnit float64     `json:"price_per_unit"`
	SupplierID   pgtype.UUID `json:"supplier_id"`
}

func (q *Queries) CreatePriceHistory(ctx context.Context, arg CreatePriceHistoryParams) (PriceHistory, error) {
	row := q.db.QueryRow(ctx, createPriceHistory, arg.IngredientID, arg.PricePerUnit, arg.SupplierID)
	var i PriceHistory
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.PricePerUnit,
		&i.SupplierID,
		&i.RecordedAt,
	)
	return i, err
}

const getLatestPrice = `-- name: GetLatestPrice :one
SELECT price_per_unit FROM price_history
WHERE ingredient_id = $1
ORDER BY recorded_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPrice(ctx context.Context, ingredientID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getLatestPrice, ingredientID)
	var price_per_unit float64
	err := row.Scan(&price_per_unit)
	return price_per_unit, err
}

const getPriceHistory = `-- name: GetPriceHistory :many
SELECT
  ph.id,
  ph.ingredient_id,
  ph.price_per_unit,
  ph.recorded_at,
  s.name AS supplier_name
FROM price_history ph
LEFT JOIN suppliers s ON s.id = ph.supplier_id
WHERE ph.ingredient_id = $1
ORDER BY ph.recorded_at DESC
LIMIT 30
`

type GetPriceHistoryRow struct {
	ID           uuid.UUID   `json:"id"`
	IngredientID uuid.UUID   `json:"ingredient_id"`
	PricePerUnit float64     `json:"price_per_unit"`
	RecordedAt   pgtype.Date `json:"recorded_at"`
	SupplierName pgtype.Text `json:"supplier_name"`
}

func (q *Queries) GetPriceHistory(ctx context.Context, ingredientID uuid.UUID) ([]GetPriceHistoryRow, error) {
	rows, err := q.db.Query(ctx, getPriceHistory, ingredientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPriceHistoryRow{}
	for rows.Next() {
		var i GetPriceHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.IngredientID,
			&i.PricePerUnit,
			&i.RecordedAt,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
