// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: production.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProductionLog = `-- name: CreateProductionLog :one
INSERT INTO production_logs (recipe_id, batch_size, actual_ingredient_cost, actual_yield, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, recipe_id, batch_size, actual_ingredient_cost, actual_yield, produced_at, notes
`

type CreateProductionLogParams struct {
	RecipeID             uuid.UUID   `json:"recipe_id"`
	BatchSize            int32       `json:"batch_size"`
	ActualIngredientCost float64     `json:"actual_ingredient_cost"`
	ActualYield          float64     `json:"actual_yield"`
	Notes                pgtype.Text `json:"notes"`
}

func (q *Queries) CreateProductionLog(ctx context.Context, arg CreateProductionLogParams) (ProductionLog, error) {
	row := q.db.QueryRow(ctx, createProductionLog,
		arg.RecipeID,
		arg.BatchSize,
		arg.ActualIngredientCost,
		arg.ActualYield,
		arg.Notes,
	)
	var i ProductionLog
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.BatchSize,
		&i.ActualIngredientCost,
		&i.ActualYield,
		&i.ProducedAt,
		&i.Notes,
	)
	return i, err
}

const deleteProductionLog = `-- name: DeleteProductionLog :exec
DELETE FROM production_logs WHERE id = $1
`

func (q *Queries) DeleteProductionLog(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductionLog, id)
	return err
}

const listProductionLogs = `-- name: ListProductionLogs :many
SELECT
  pl.id,
  pl.recipe_id,
  pl.batch_size,
  pl.actual_ingredient_cost,
  pl.actual_yield,
  pl.produced_at,
  pl.notes,
  r.name        AS recipe_name,
  r.batch_yield AS expected_yield,
  r.yield_unit
FROM production_logs pl
JOIN recipes r ON r.id = pl.recipe_id
ORDER BY pl.produced_at DESC
LIMIT 100
`

type ListProductionLogsRow struct {
	ID                   uuid.UUID          `json:"id"`
	RecipeID             uuid.UUID          `json:"recipe_id"`
	BatchSize            int32              `json:"batch_size"`
	ActualIngredientCost float64            `json:"actual_ingredient_cost"`
	ActualYield          float64            `json:"actual_yield"`
	ProducedAt           pgtype.Timestamptz `json:"produced_at"`
	Notes                pgtype.Text        `json:"notes"`
	RecipeName           string             `json:"recipe_name"`
	ExpectedYield        int32              `json:"expected_yield"`
	YieldUnit            string             `json:"yield_unit"`
}

func (q *Queries) ListProductionLogs(ctx context.Context) ([]ListProductionLogsRow, error) {
	rows, err := q.db.Query(ctx, listProductionLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductionLogsRow{}
	for rows.Next() {
		var i ListProductionLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.BatchSize,
			&i.ActualIngredientCost,
			&i.ActualYield,
			&i.ProducedAt,
			&i.Notes,
			&i.RecipeName,
			&i.ExpectedYield,
			&i.YieldUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionLogsByRecipe = `-- name: ListProductionLogsByRecipe :many
SELECT
  pl.id,
  pl.recipe_id,
  pl.batch_size,
  pl.actual_ingredient_cost,
  pl.actual_yield,
  pl.produced_at,
  pl.notes,
  r.name        AS recipe_name,
  r.batch_yield AS expected_yield,
  r.yield_unit
FROM production_logs pl
JOIN recipes r ON r.id = pl.recipe_id
WHERE pl.recipe_id = $1
ORDER BY pl.produced_at DESC
`

type ListProductionLogsByRecipeRow struct {
	ID                   uuid.UUID          `json:"id"`
	RecipeID             uuid.UUID          `json:"recipe_id"`
	BatchSize            int32              `json:"batch_size"`
	ActualIngredientCost float64            `json:"actual_ingredient_cost"`
	ActualYield          float64            `json:"actual_yield"`
	ProducedAt           pgtype.Timestamptz `json:"produced_at"`
	Notes                pgtype.Text        `json:"notes"`
	RecipeName           string             `json:"recipe_name"`
	ExpectedYield        int32              `json:"expected_yield"`
	YieldUnit            string             `json:"yield_unit"`
}

func (q *Queries) ListProductionLogsByRecipe(ctx context.Context, recipeID uuid.UUID) ([]ListProductionLogsByRecipeRow, error) {
	rows, err := q.db.Query(ctx, listProductionLogsByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductionLogsByRecipeRow{}
	for rows.Next() {
		var i ListProductionLogsByRecipeRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.BatchSize,
			&i.ActualIngredientCost,
			&i.ActualYield,
			&i.ProducedAt,
			&i.Notes,
			&i.RecipeName,
			&i.ExpectedYield,
			&i.YieldUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
