// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCOGSSnapshot(ctx context.Context, arg CreateCOGSSnapshotParams) (CogsSnapshot, error)
	CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error)
	CreateLaborProfile(ctx context.Context, arg CreateLaborProfileParams) (LaborProfile, error)
	CreateOverheadTemplate(ctx context.Context, arg CreateOverheadTemplateParams) (OverheadTemplate, error)
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	CreateRecipeLine(ctx context.Context, arg CreateRecipeLineParams) (RecipeLine, error)
	DeleteIngredient(ctx context.Context, id uuid.UUID) error
	DeleteLaborProfile(ctx context.Context, id uuid.UUID) error
	DeleteOverheadTemplate(ctx context.Context, id uuid.UUID) error
	DeleteRecipe(ctx context.Context, id uuid.UUID) error
	DeleteRecipeLines(ctx context.Context, recipeID uuid.UUID) error
	GetIngredient(ctx context.Context, id uuid.UUID) (Ingredient, error)
	GetOverheadTemplate(ctx context.Context, id uuid.UUID) (OverheadTemplate, error)
	GetRecipe(ctx context.Context, id uuid.UUID) (Recipe, error)
	GetRecipeLines(ctx context.Context, recipeID uuid.UUID) ([]GetRecipeLinesRow, error)
	ListAllRecipes(ctx context.Context) ([]Recipe, error)
	ListCOGSSnapshots(ctx context.Context) ([]ListCOGSSnapshotsRow, error)
	ListCOGSSnapshotsByRecipe(ctx context.Context, recipeID uuid.UUID) ([]CogsSnapshot, error)
	ListIngredients(ctx context.Context) ([]Ingredient, error)
	ListLaborProfiles(ctx context.Context) ([]LaborProfile, error)
	ListOverheadTemplates(ctx context.Context) ([]OverheadTemplate, error)
	ListRecipes(ctx context.Context) ([]Recipe, error)
	ListSubRecipes(ctx context.Context) ([]Recipe, error)
	UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error)
	UpdateOverheadTemplate(ctx context.Context, arg UpdateOverheadTemplateParams) (OverheadTemplate, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)
}

var _ Querier = (*Queries)(nil)
