// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCOGSSnapshot(ctx context.Context, arg CreateCOGSSnapshotParams) (CogsSnapshot, error)
	CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error)
	CreateLaborProfile(ctx context.Context, arg CreateLaborProfileParams) (LaborProfile, error)
	CreateOverheadTemplate(ctx context.Context, arg CreateOverheadTemplateParams) (OverheadTemplate, error)
	CreatePriceHistory(ctx context.Context, arg CreatePriceHistoryParams) (PriceHistory, error)
	CreateProductionLog(ctx context.Context, arg CreateProductionLogParams) (ProductionLog, error)
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	CreateRecipeLine(ctx context.Context, arg CreateRecipeLineParams) (RecipeLine, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	DeleteCOGSSnapshot(ctx context.Context, id uuid.UUID) error
	DeleteIngredient(ctx context.Context, id uuid.UUID) error
	DeleteLaborProfile(ctx context.Context, id uuid.UUID) error
	DeleteOverheadTemplate(ctx context.Context, id uuid.UUID) error
	DeleteProductionLog(ctx context.Context, id uuid.UUID) error
	DeleteRecipe(ctx context.Context, id uuid.UUID) error
	DeleteRecipeLines(ctx context.Context, recipeID uuid.UUID) error
	DeleteSupplier(ctx context.Context, id uuid.UUID) error
	GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error)
	GetIngredient(ctx context.Context, id uuid.UUID) (Ingredient, error)
	GetIngredientUsageReport(ctx context.Context) ([]GetIngredientUsageReportRow, error)
	GetLaborProfile(ctx context.Context, id uuid.UUID) (LaborProfile, error)
	GetLatestPrice(ctx context.Context, ingredientID uuid.UUID) (float64, error)
	GetOverheadTemplate(ctx context.Context, id uuid.UUID) (OverheadTemplate, error)
	GetPriceHistory(ctx context.Context, ingredientID uuid.UUID) ([]GetPriceHistoryRow, error)
	GetRecentSnapshots(ctx context.Context) ([]GetRecentSnapshotsRow, error)
	GetRecipe(ctx context.Context, id uuid.UUID) (Recipe, error)
	GetRecipeLines(ctx context.Context, recipeID uuid.UUID) ([]GetRecipeLinesRow, error)
	GetSupplier(ctx context.Context, id uuid.UUID) (Supplier, error)
	GetSupplierIngredients(ctx context.Context, supplierID pgtype.UUID) ([]Ingredient, error)
	GetTopIngredientsByCost(ctx context.Context) ([]GetTopIngredientsByCostRow, error)
	ListAllRecipes(ctx context.Context) ([]Recipe, error)
	ListCOGSHistory(ctx context.Context) ([]ListCOGSHistoryRow, error)
	ListCOGSHistoryByRecipe(ctx context.Context, recipeID uuid.UUID) ([]ListCOGSHistoryByRecipeRow, error)
	ListIngredients(ctx context.Context) ([]Ingredient, error)
	ListLaborProfiles(ctx context.Context) ([]LaborProfile, error)
	ListOverheadTemplates(ctx context.Context) ([]OverheadTemplate, error)
	ListProductionLogs(ctx context.Context) ([]ListProductionLogsRow, error)
	ListProductionLogsByRecipe(ctx context.Context, recipeID uuid.UUID) ([]ListProductionLogsByRecipeRow, error)
	ListRecipes(ctx context.Context) ([]Recipe, error)
	ListSubRecipes(ctx context.Context) ([]Recipe, error)
	ListSuppliers(ctx context.Context) ([]Supplier, error)
	UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error)
	UpdateLaborProfile(ctx context.Context, arg UpdateLaborProfileParams) (LaborProfile, error)
	UpdateOverheadTemplate(ctx context.Context, arg UpdateOverheadTemplateParams) (OverheadTemplate, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error)
}

var _ Querier = (*Queries)(nil)
