// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (name, category, batch_yield, yield_unit, is_sub_recipe)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, category, batch_yield, yield_unit, is_sub_recipe, updated_at
`

type CreateRecipeParams struct {
	Name        string      `json:"name"`
	Category    pgtype.Text `json:"category"`
	BatchYield  int32       `json:"batch_yield"`
	YieldUnit   string      `json:"yield_unit"`
	IsSubRecipe bool        `json:"is_sub_recipe"`
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, createRecipe,
		arg.Name,
		arg.Category,
		arg.BatchYield,
		arg.YieldUnit,
		arg.IsSubRecipe,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.BatchYield,
		&i.YieldUnit,
		&i.IsSubRecipe,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecipeLine = `-- name: CreateRecipeLine :one
INSERT INTO recipe_lines (recipe_id, ingredient_id, sub_recipe_id, quantity, unit)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, recipe_id, ingredient_id, sub_recipe_id, quantity, unit
`

type CreateRecipeLineParams struct {
	RecipeID     uuid.UUID   `json:"recipe_id"`
	IngredientID pgtype.UUID `json:"ingredient_id"`
	SubRecipeID  pgtype.UUID `json:"sub_recipe_id"`
	Quantity     float64     `json:"quantity"`
	Unit         string      `json:"unit"`
}

func (q *Queries) CreateRecipeLine(ctx context.Context, arg CreateRecipeLineParams) (RecipeLine, error) {
	row := q.db.QueryRow(ctx, createRecipeLine,
		arg.RecipeID,
		arg.IngredientID,
		arg.SubRecipeID,
		arg.Quantity,
		arg.Unit,
	)
	var i RecipeLine
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.IngredientID,
		&i.SubRecipeID,
		&i.Quantity,
		&i.Unit,
	)
	return i, err
}

const deleteRecipe = `-- name: DeleteRecipe :exec
DELETE FROM recipes WHERE id = $1
`

func (q *Queries) DeleteRecipe(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecipe, id)
	return err
}

const deleteRecipeLines = `-- name: DeleteRecipeLines :exec
DELETE FROM recipe_lines WHERE recipe_id = $1
`

func (q *Queries) DeleteRecipeLines(ctx context.Context, recipeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecipeLines, recipeID)
	return err
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, name, category, batch_yield, yield_unit, is_sub_recipe, updated_at FROM recipes WHERE id = $1
`

func (q *Queries) GetRecipe(ctx context.Context, id uuid.UUID) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.BatchYield,
		&i.YieldUnit,
		&i.IsSubRecipe,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeLines = `-- name: GetRecipeLines :many
SELECT
    rl.id,
    rl.recipe_id,
    rl.ingredient_id,
    rl.sub_recipe_id,
    rl.quantity,
    rl.unit,
    i.name           AS ingredient_name,
    i.unit           AS ingredient_unit,
    i.price_per_unit,
    i.waste_pct
FROM recipe_lines rl
LEFT JOIN ingredients i ON i.id = rl.ingredient_id
WHERE rl.recipe_id = $1
`

type GetRecipeLinesRow struct {
	ID             uuid.UUID      `json:"id"`
	RecipeID       uuid.UUID      `json:"recipe_id"`
	IngredientID   pgtype.UUID    `json:"ingredient_id"`
	SubRecipeID    pgtype.UUID    `json:"sub_recipe_id"`
	Quantity       float64        `json:"quantity"`
	Unit           string         `json:"unit"`
	IngredientName pgtype.Text    `json:"ingredient_name"`
	IngredientUnit pgtype.Text    `json:"ingredient_unit"`
	PricePerUnit   pgtype.Numeric `json:"price_per_unit"`
	WastePct       pgtype.Numeric `json:"waste_pct"`
}

func (q *Queries) GetRecipeLines(ctx context.Context, recipeID uuid.UUID) ([]GetRecipeLinesRow, error) {
	rows, err := q.db.Query(ctx, getRecipeLines, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecipeLinesRow{}
	for rows.Next() {
		var i GetRecipeLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.IngredientID,
			&i.SubRecipeID,
			&i.Quantity,
			&i.Unit,
			&i.IngredientName,
			&i.IngredientUnit,
			&i.PricePerUnit,
			&i.WastePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRecipes = `-- name: ListAllRecipes :many
SELECT id, name, category, batch_yield, yield_unit, is_sub_recipe, updated_at FROM recipes ORDER BY name
`

func (q *Queries) ListAllRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listAllRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.BatchYield,
			&i.YieldUnit,
			&i.IsSubRecipe,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
SELECT id, name, category, batch_yield, yield_unit, is_sub_recipe, updated_at FROM recipes WHERE is_sub_recipe = FALSE ORDER BY name
`

func (q *Queries) ListRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.BatchYield,
			&i.YieldUnit,
			&i.IsSubRecipe,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubRecipes = `-- name: ListSubRecipes :many
SELECT id, name, category, batch_yield, yield_unit, is_sub_recipe, updated_at FROM recipes WHERE is_sub_recipe = TRUE ORDER BY name
`

func (q *Queries) ListSubRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listSubRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.BatchYield,
			&i.YieldUnit,
			&i.IsSubRecipe,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipes
SET name = $2, category = $3, batch_yield = $4, yield_unit = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, name, category, batch_yield, yield_unit, is_sub_recipe, updated_at
`

type UpdateRecipeParams struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	Category   pgtype.Text `json:"category"`
	BatchYield int32       `json:"batch_yield"`
	YieldUnit  string      `json:"yield_unit"`
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, updateRecipe,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.BatchYield,
		arg.YieldUnit,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.BatchYield,
		&i.YieldUnit,
		&i.IsSubRecipe,
		&i.UpdatedAt,
	)
	return i, err
}
