// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
  (SELECT COUNT(*) FROM ingredients)         AS ingredient_count,
  (SELECT COUNT(*) FROM recipes WHERE is_sub_recipe = FALSE) AS recipe_count,
  (SELECT COUNT(*) FROM suppliers)           AS supplier_count,
  (SELECT COUNT(*) FROM cogs_snapshots)      AS snapshot_count
`

type GetDashboardStatsRow struct {
	IngredientCount int64 `json:"ingredient_count"`
	RecipeCount     int64 `json:"recipe_count"`
	SupplierCount   int64 `json:"supplier_count"`
	SnapshotCount   int64 `json:"snapshot_count"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.IngredientCount,
		&i.RecipeCount,
		&i.SupplierCount,
		&i.SnapshotCount,
	)
	return i, err
}

const getIngredientUsageReport = `-- name: GetIngredientUsageReport :many
SELECT
  i.id,
  i.name,
  i.unit,
  i.price_per_unit,
  i.waste_pct,
  COUNT(DISTINCT rl.recipe_id) AS recipe_count,
  COALESCE(
    STRING_AGG(DISTINCT r.name, ', ' ORDER BY r.name),
    ''
  ) AS used_in_recipes,
  SUM(rl.quantity) AS total_quantity_used
FROM ingredients i
LEFT JOIN recipe_lines rl ON rl.ingredient_id = i.id
LEFT JOIN recipes r ON r.id = rl.recipe_id
GROUP BY i.id
ORDER BY recipe_count DESC, i.price_per_unit DESC
`

type GetIngredientUsageReportRow struct {
	ID                uuid.UUID   `json:"id"`
	Name              string      `json:"name"`
	Unit              string      `json:"unit"`
	PricePerUnit      float64     `json:"price_per_unit"`
	WastePct          float64     `json:"waste_pct"`
	RecipeCount       int64       `json:"recipe_count"`
	UsedInRecipes     interface{} `json:"used_in_recipes"`
	TotalQuantityUsed int64       `json:"total_quantity_used"`
}

func (q *Queries) GetIngredientUsageReport(ctx context.Context) ([]GetIngredientUsageReportRow, error) {
	rows, err := q.db.Query(ctx, getIngredientUsageReport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetIngredientUsageReportRow{}
	for rows.Next() {
		var i GetIngredientUsageReportRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unit,
			&i.PricePerUnit,
			&i.WastePct,
			&i.RecipeCount,
			&i.UsedInRecipes,
			&i.TotalQuantityUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentSnapshots = `-- name: GetRecentSnapshots :many
SELECT
  cs.id,
  cs.cost_per_unit,
  cs.suggested_price,
  cs.margin_pct,
  cs.calculated_at,
  r.name AS recipe_name
FROM cogs_snapshots cs
JOIN recipes r ON r.id = cs.recipe_id
ORDER BY cs.calculated_at DESC
LIMIT 5
`

type GetRecentSnapshotsRow struct {
	ID             uuid.UUID          `json:"id"`
	CostPerUnit    float64            `json:"cost_per_unit"`
	SuggestedPrice float64            `json:"suggested_price"`
	MarginPct      float64            `json:"margin_pct"`
	CalculatedAt   pgtype.Timestamptz `json:"calculated_at"`
	RecipeName     string             `json:"recipe_name"`
}

func (q *Queries) GetRecentSnapshots(ctx context.Context) ([]GetRecentSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, getRecentSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentSnapshotsRow{}
	for rows.Next() {
		var i GetRecentSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.CostPerUnit,
			&i.SuggestedPrice,
			&i.MarginPct,
			&i.CalculatedAt,
			&i.RecipeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopIngredientsByCost = `-- name: GetTopIngredientsByCost :many
SELECT
  i.id,
  i.name,
  i.unit,
  i.price_per_unit,
  COUNT(rl.id) AS used_in_recipes
FROM ingredients i
LEFT JOIN recipe_lines rl ON rl.ingredient_id = i.id
GROUP BY i.id
ORDER BY i.price_per_unit DESC
LIMIT 8
`

type GetTopIngredientsByCostRow struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Unit          string    `json:"unit"`
	PricePerUnit  float64   `json:"price_per_unit"`
	UsedInRecipes int64     `json:"used_in_recipes"`
}

func (q *Queries) GetTopIngredientsByCost(ctx context.Context) ([]GetTopIngredientsByCostRow, error) {
	rows, err := q.db.Query(ctx, getTopIngredientsByCost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopIngredientsByCostRow{}
	for rows.Next() {
		var i GetTopIngredientsByCostRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unit,
			&i.PricePerUnit,
			&i.UsedInRecipes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
