// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suppliers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (name, contact)
VALUES ($1, $2)
RETURNING id, name, contact, created_at
`

type CreateSupplierParams struct {
	Name    string      `json:"name"`
	Contact pgtype.Text `json:"contact"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier, arg.Name, arg.Contact)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Contact,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSupplier = `-- name: DeleteSupplier :exec
DELETE FROM suppliers WHERE id = $1
`

func (q *Queries) DeleteSupplier(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSupplier, id)
	return err
}

const getSupplier = `-- name: GetSupplier :one
SELECT id, name, contact, created_at FROM suppliers WHERE id = $1
`

func (q *Queries) GetSupplier(ctx context.Context, id uuid.UUID) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplier, id)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Contact,
		&i.CreatedAt,
	)
	return i, err
}

const getSupplierIngredients = `-- name: GetSupplierIngredients :many
SELECT id, name, sku, unit, price_per_unit, waste_pct, supplier_id, updated_at FROM ingredients WHERE supplier_id = $1 ORDER BY name
`

func (q *Queries) GetSupplierIngredients(ctx context.Context, supplierID pgtype.UUID) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, getSupplierIngredients, supplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ingredient{}
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Unit,
			&i.PricePerUnit,
			&i.WastePct,
			&i.SupplierID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, name, contact, created_at FROM suppliers ORDER BY name
`

func (q *Queries) ListSuppliers(ctx context.Context) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Contact,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers
SET name = $2, contact = $3
WHERE id = $1
RETURNING id, name, contact, created_at
`

type UpdateSupplierParams struct {
	ID      uuid.UUID   `json:"id"`
	Name    string      `json:"name"`
	Contact pgtype.Text `json:"contact"`
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, updateSupplier, arg.ID, arg.Name, arg.Contact)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Contact,
		&i.CreatedAt,
	)
	return i, err
}
